### ISSUE TITLE
Front Page with new content type

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/shasetsu#2]
FYI

![shasetsu-cards](https://user-images.githubusercontent.com/3144571/165410224-dbd00945-7ff4-48a4-9e0a-fa4be1eb73ab.png)

**Comment by olafgrabienski** [comment]
Thanks @stpaultim for the screenshot.

So, the contrast between the `#f5f5f5` background of the hero block and the `#f2f2f2` background of the new cards block is pretty low. My ideas so far:

(1) increase the contrast slightly: `#eeeeee` as cards background
(2) align the background colors: `#f5f5f5` for both blocks

My favorite is (2), in my opinion it's more in line with the smooth look and feel of Shasetsu.

**Comment by olafgrabienski** [comment]
Reminder: consider also the recommended configuration (Hero block in content region), see https://github.com/backdrop-contrib/shasetsu#usage

- style cards differently for content region
- update Readme

**Comment by olafgrabienski** [comment]
Card styles added and README adapted:

- [Add styles for the new Card content type grid](https://github.com/backdrop-contrib/shasetsu/commit/c554edcacedd4ebb16a5f0d932b8fe447b118513)
- [Adapt README for new Card content type](https://github.com/backdrop-contrib/shasetsu/commit/c435d1b0947dd378403c53096be46529e1b3063d)
